name: Publish

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: Roblox/setup-foreman@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Report tool versions
      run: rojo --version

    - name: Upload
      run: rojo upload .github/module.project.json --asset_id 9809420845 --cookie $ROBLOSECURITY
      env:
        ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}