name: Publish

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: Roblox/setup-foreman@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload
      run: rojo upload deploy.project.json --cookie "$ROBLOSECURITY" --asset_id 9809420845
      env:
        ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}