name: publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build MainModule
      - shell: bash
        run: echo "$TEST"
        env:
          TEST: ${{ secrets.TEST }}
        
        
      # - name: Publish MainModule
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: "${{ secrets.PUBLISH_URL }}/${{ secrets.MODULE_ID }}"
      #     method: "POST"
      #     contentType: "multipart/form-data"
      #     files: '{ "file": "module.rbxm" }'
      #     customHeaders: '{ "x-auth-token": "${{ secrets.PUBLISH_TOKEN }}" }'
      #     timeout: 10000